#!/usr/bin/env php
<?php

declare(strict_types=1);

use YiiPress\Environment;
use YiiPress\Console\ApplicationRunner;

require_once __DIR__ . '/src/autoload.php';

// Run console application runner
$runner = new ApplicationRunner(
    rootPath: __DIR__,
    debug: Environment::appDebug(),
    checkEvents: Environment::appDebug(),
    environment: Environment::appEnv(),
);
$runner->run();
