<?php

declare(strict_types=1);

namespace YiiPress\Console;

use RuntimeException;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Yiisoft\Files\FileHelper;
use Yiisoft\Yii\Console\ExitCode;

use function array_keys;
use function dirname;
use function file_exists;
use function file_put_contents;
use function sprintf;
use function str_starts_with;

#[AsCommand(
    name: 'init',
    description: 'Initialize a YiiPress content directory',
)]
final class InitCommand extends Command
{
    public function __construct(private readonly string $rootPath)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addUsage('--content-dir=content');
        $this->addOption(
            'content-dir',
            'c',
            InputOption::VALUE_REQUIRED,
            'Path to the content directory',
            'content',
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        /** @var string $contentDirOption */
        $contentDirOption = $input->getOption('content-dir');
        $contentDir = $this->resolvePath($contentDirOption, $this->rootPath);

        $files = [
            $contentDir . '/config.yaml' => $this->siteConfig(),
            $contentDir . '/navigation.yaml' => $this->navigation(),
            $contentDir . '/page/_collection.yaml' => $this->pageCollection(),
            $contentDir . '/blog/_collection.yaml' => $this->blogCollection(),
        ];

        foreach (array_keys($files) as $filePath) {
            if (file_exists($filePath)) {
                $output->writeln("<error>Path already exists: $filePath</error>");
                return ExitCode::DATAERR;
            }
        }

        foreach ($files as $filePath => $contents) {
            FileHelper::ensureDirectory(dirname($filePath), 0o755);

            if (file_put_contents($filePath, $contents) === false) {
                throw new RuntimeException(sprintf('File "%s" was not written', $filePath));
            }

            $output->writeln("Created: <info>$filePath</info>");
        }

        return ExitCode::OK;
    }

    private function siteConfig(): string
    {
        return <<<YAML
title: "My YiiPress Site"
description: "A static site generated by YiiPress"
base_url: "https://example.com"
languages: ["en"]
charset: "UTF-8"
date_format: "F j, Y"
entries_per_page: 10
permalink: "/:collection/:slug/"
taxonomies:
  - tags
  - categories

YAML;
    }

    private function navigation(): string
    {
        return <<<YAML
main:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"

YAML;
    }

    private function pageCollection(): string
    {
        return <<<YAML
title: "Pages"
permalink: "/:slug/"
sort_by: "weight"
sort_order: "asc"
entries_per_page: 0
feed: false
listing: false

YAML;
    }

    private function blogCollection(): string
    {
        return <<<YAML
title: "Blog"
description: "Latest posts"
permalink: "/blog/:slug/"
sort_by: "date"
sort_order: "desc"
entries_per_page: 10
feed: true
listing: true

YAML;
    }

    private function resolvePath(string $path, string $rootPath): string
    {
        if (str_starts_with($path, '/')) {
            return $path;
        }

        return $rootPath . '/' . $path;
    }
}
