name: Static Analysis

on:
  push:
    branches:
      - master
    paths: &analysis-paths
      - 'src/**'
      - 'config/**'
      - 'tests/**'
      - 'yii'
      - 'composer.json'
      - 'composer.lock'
      - 'psalm.xml'
      - 'psalm-baseline.xml'
      - 'stubs/**'
      - 'phpstan.neon'
      - 'phpstan-baseline.neon'
      - 'composer-dependency-analyser.php'
      - 'Makefile'
      - 'docker/**'
      - '.github/workflows/static-analysis.yml'
  pull_request:
    branches:
      - master
    paths: *analysis-paths
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  psalm:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Install dependencies
        run: make -- composer install --no-progress --no-interaction

      - name: Run Psalm
        run: make psalm

  phpstan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: make -- composer install --no-progress --no-interaction
      - name: Run PHPStan
        run: make phpstan

  composer-dependency-analyser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Install dependencies
        run: make -- composer install --no-progress --no-interaction
      - name: Run Composer Dependency Analyser
        run: make composer-dependency-analyser
