name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Install dependencies
        run: make -- composer install --no-progress --no-interaction

      - name: Run Psalm
        run: make psalm

      - name: Run Composer Dependency Analyser
        run: make composer-dependency-analyser
