name: Workflow Security

on:
  pull_request:
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  push:
    branches:
      - master
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Analyse workflows
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          advanced-security: true
          annotations: false
          config: .github/zizmor.yml
          min-severity: high
          persona: 'pedantic'
